Add `libswmhack_enabled` option
conformal/spectrwm pull request #563
Opened 2024-02-10 15:10 UTC by andreabolognani

Allows users a convenient way to opt-out of `libswmhack.so` usage if they so desire.

2024-02-13 22:37 UTC, andreabolognani commented
Added `spectrwm.conf` snippet for the new option.

2024-02-14 10:25 UTC, xplshn commented
This is great., I'd actually like to learn what libswmhack.so does tho

2024-02-14 22:41 UTC, andreabolognani commented
I feel that the documentation in the "SWMHACK" section of the manual page does a pretty good job at explaining what `libswmhack.so` is all about, but if you have specific grievances about it I'm sure they can be looked into...

2024-02-14 23:05 UTC, marcopeereboom requested changes
This kind of adds a hack to hack for a specific app. I do not love this. I’d like to know the actual root cause before pushing something in that frankly looks incorrect.

2024-02-15 00:00 UTC, andreabolognani commented
@marcopeereboom it's not about any specific app, it's about the general "stickiness" of workspace assignment.

The problem is that setting the value of `_SWM_WS` in the process' environment decides where the window is going to be placed, but that value is 1) inherited by child processes and 2) not updated as windows are moved across workspaces.

So once a window has been spawned on a certain workspace, all subsequent windows are going to be spawned in that original workspace, even if the first window has been moved in the meantime. This applies to terminals and the processes spawned via them, as described in the commit message, as well as other applications.

For example, I just tried a simple text editor (mousepad from Xfce) and confirmed that its "new window" functionality is affected by this: if I spawn the editor on workspace 1, move it to workspace 2, then select "new window", said new window will show up on workspace 1.

I personally find that this behavior gets in my way, and I expect that new users are going to be particularly baffled by it: if you don't already know what's going on, you will certainly get the impression that the window has simply not been created, since there is zero indication that it has simply been spawned on a different workspace.

The documented way to avoid this "spawn-in-workspace" behavior is to unset `_SWM_WS`, and while that certainly works when spawning applications from a terminal, it can't be used in the case of e.g. running mousepad from dmenu. Regardless, having to opt-out of this behavior every single time I launch an application gets old real fast.

So what I'm looking for is a way to simply disable the "spawn-in-workspace" behavior globally. I'm aware that I'm losing some functionality in the process, but it's functionality that I don't personally need so I'm quite happy with the trade-off. The cleaner process environment, and being able to avoid the use of `LD_PRELOAD` are just pleasant side-effects.

The specific implementation in this PR is just the simplest one I could cobble together. If there's a different design that you would prefer to see, I'm open to exploring it. I only really care about the end result.

2024-02-15 00:07 UTC, LordReg commented
This is a duplicate of #415

@andreabolognani It is already possible to force windows to map on the current workspace via conf:
```
quirk[.*] = IGNORESPAWNWS
```

With 3.6:
```
quirk[.*] += IGNORESPAWNWS
```

2024-02-15 00:20 UTC, andreabolognani commented
> This is a duplicate of #415

The patch is almost identical too, how fun :)

> It is already possible to force windows to map on the current workspace via conf:
> 
> ```
> quirk[.*] = IGNORESPAWNWS
> ```
> 
> With 3.6:
> 
> ```
> quirk[.*] += IGNORESPAWNWS
> ```

I gave it a quick try and it does indeed seem to do exactly what I want. Thanks!

I will admit that I'm still not a fan of `LD_PRELOAD` and `_SWM_WS` showing up all over the place even though I'm not interested in any of the functionality that it's implemented through them, but as I said that's a secondary concern.

I'll rework the series so that it simply updates the documentation to advertise this possibility more prominently. The first patch is already good as is, I think.

2024-02-15 00:35 UTC, andreabolognani commented
@LordReg done.

Being able to use `+=` instead of `=` would be a big improvement here, since IIUC the latter would overwrite the default quirks while the former wouldn't.

I don't quite understand how the release process for spectrwm works, so please bear with me. Would updating the documentation to use `+=` and then re-targeting the PR to the `release3.6` branch (the only one where the `+=` functionality is implemented) be the right thing to do?

2024-02-15 00:41 UTC, andreabolognani commented
Additional question: to ensure the "spawn-in-workspace" behavior is disabled completely, would it be better to use

```
quirk[.*] += IGNORESPAWNWS + IGNOREPID
```

instead? I'll admit that I don't understand the impact of `_SWM_PID` on workspace selection as well as that of `_SWM_WS`.

2024-02-15 01:46 UTC, LordReg commented
Yes, please target/base any changes on [release3.6](/conformal/spectrwm/tree/release3.6) 

The quirks were designed to workaround specific issues:
`IGNORESPAWNWS` works around the "new window" issue you described.
`IGNOREPID` may be needed for programs that reuse a process on subsequent invocations.

`IGNORESPAWNWS` is typically enough to address grievances, but combining both fully disables *spawn-in-workspace*.

Also, `_SWM_PID` is a fallback when programs don't set `_NET_WM_PID` on their windows.

2024-02-15 02:58 UTC, andreabolognani commented
@LordReg done, thanks a lot for the explanation!

Unrelated, but I would love it if https://github.com/conformal/spectrwm/pull/556 could make it into 3.6 as well. Should I do the rebase/retarget dance there too?

2024-02-17 12:25 UTC, merged